before_install:
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - ./travis_before_install

install: "pip install -r requirements.txt"  
language: python
python:
  - "3.7"
script: robot Samples/test.robot
