# This is a basic workflow to help you get started with Actions

name: Push / pull CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 robot_test:
    runs-on: windows-latest
    
    steps:
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
     
      - name: install dependecies
        run: |
            pip install WatchUi
            pip install robotframework
            pip install robotframework-seleniumlibrary
      - name: start test
        run: robot ./Samples/test.robot
        

      
