# This is a basic workflow to help you get started with Actions

name: Push / pull CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v0.1
              RUN apt-get update && apt-get install -y \
              python-pip
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/Samples
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/Samples
      
